plugins:
  - jekyll-include-cache

remote_theme: "pmarsceill/just-the-docs"

# Name of your site (displayed in the header)
name: NOVA API Client for PHP

# Name of website (site.title)
title: A NOVA API Client for PHP

# Short description of your site
description: NOVA API Client
