plugins:
  - jekyll-include-cache

remote_theme: "pmarsceill/just-the-docs"

# Name of your site (displayed in the header)
name: NOVA API Client

# Name of website (site.title)
title: NOVA API Client

# Short description of your site
description: NOVA API Client
